-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.affitti_casa
(
    catastale character varying(20) COLLATE pg_catalog."default" NOT NULL,
    data_affitto date NOT NULL,
    filiale_proponente character varying(20) COLLATE pg_catalog."default" NOT NULL,
    filiale_venditrice character varying(20) COLLATE pg_catalog."default" NOT NULL,
    prezzo_affitto numeric(15, 2) NOT NULL,
    durata_contratto integer NOT NULL,
    CONSTRAINT affitti_casa_pkey PRIMARY KEY (catastale, data_affitto)
);

CREATE TABLE IF NOT EXISTS public.case_in_affitto
(
    catastale character varying(20) COLLATE pg_catalog."default" NOT NULL,
    indirizzo character varying(255) COLLATE pg_catalog."default" NOT NULL,
    civico character varying(10) COLLATE pg_catalog."default" NOT NULL,
    tipo_affitto tipo_affitto NOT NULL,
    bagno_personale boolean NOT NULL,
    prezzo_mensile numeric(15, 2) NOT NULL,
    filiale_proponente character varying(20) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT case_in_affitto_pkey PRIMARY KEY (catastale)
);

CREATE TABLE IF NOT EXISTS public.case_in_vendita
(
    catastale character varying(20) COLLATE pg_catalog."default" NOT NULL,
    indirizzo character varying(255) COLLATE pg_catalog."default" NOT NULL,
    numero_civico character varying(10) COLLATE pg_catalog."default" NOT NULL,
    piano integer NOT NULL,
    metri integer NOT NULL,
    vani integer NOT NULL,
    prezzo numeric(15, 2) NOT NULL,
    stato stato_casa NOT NULL,
    filiale_proponente character varying(20) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT case_in_vendita_pkey PRIMARY KEY (catastale)
);

CREATE TABLE IF NOT EXISTS public.filiali
(
    partita_iva character varying(20) COLLATE pg_catalog."default" NOT NULL,
    nome character varying(255) COLLATE pg_catalog."default" NOT NULL,
    indirizzo_sede character varying(255) COLLATE pg_catalog."default" NOT NULL,
    civico character varying(10) COLLATE pg_catalog."default" NOT NULL,
    telefono character varying(15) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT filiali_pkey PRIMARY KEY (partita_iva)
);

CREATE TABLE IF NOT EXISTS public.utenti
(
    username character varying COLLATE pg_catalog."default" NOT NULL,
    password character varying(255) COLLATE pg_catalog."default" NOT NULL,
    tipo_utente tipo_utente NOT NULL,
    CONSTRAINT utenti_pkey PRIMARY KEY (username)
);

CREATE TABLE IF NOT EXISTS public.vendite_casa
(
    catastale character varying(20) COLLATE pg_catalog."default" NOT NULL,
    data_vendita date NOT NULL,
    filiale_proponente character varying(20) COLLATE pg_catalog."default" NOT NULL,
    filiale_venditrice character varying(20) COLLATE pg_catalog."default" NOT NULL,
    prezzo_vendita numeric(15, 2) NOT NULL,
    CONSTRAINT vendite_casa_pkey PRIMARY KEY (catastale, data_vendita)
);

ALTER TABLE IF EXISTS public.affitti_casa
    ADD CONSTRAINT affitti_casa_catastale_fkey FOREIGN KEY (catastale)
    REFERENCES public.case_in_affitto (catastale) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.affitti_casa
    ADD CONSTRAINT affitti_casa_filiale_proponente_fkey FOREIGN KEY (filiale_proponente)
    REFERENCES public.filiali (partita_iva) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.affitti_casa
    ADD CONSTRAINT affitti_casa_filiale_venditrice_fkey FOREIGN KEY (filiale_venditrice)
    REFERENCES public.filiali (partita_iva) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.case_in_affitto
    ADD CONSTRAINT case_in_affitto_filiale_proponente_fkey FOREIGN KEY (filiale_proponente)
    REFERENCES public.filiali (partita_iva) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.case_in_vendita
    ADD CONSTRAINT case_in_vendita_filiale_proponente_fkey FOREIGN KEY (filiale_proponente)
    REFERENCES public.filiali (partita_iva) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.vendite_casa
    ADD CONSTRAINT vendite_casa_catastale_fkey FOREIGN KEY (catastale)
    REFERENCES public.case_in_vendita (catastale) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.vendite_casa
    ADD CONSTRAINT vendite_casa_filiale_proponente_fkey FOREIGN KEY (filiale_proponente)
    REFERENCES public.filiali (partita_iva) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.vendite_casa
    ADD CONSTRAINT vendite_casa_filiale_venditrice_fkey FOREIGN KEY (filiale_venditrice)
    REFERENCES public.filiali (partita_iva) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;